Capstone_Project
gersonhiggins/capstone_project pull request #1
Opened 2023-04-19 16:32 UTC by gersonhiggins

Add Index.html for homepage and about.html for about page
add styles with css
Add png files 
add Js for menu, foods menu and DOM objects
checked linters 
Add readme file and License MIT
[Loom Video](https://www.loom.com/share/1c2e0ca3883746ea81c83627abfdfeaf) - Little Reference of this project

2023-04-19 17:14 UTC, Ismailco reviewed
Hi @gersonhiggins, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should use GitHub flow, kindly make sure to open a PR from your branch to the `main` branch not `main22`, also make sure to add a live demo link to your README file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 18:37 UTC, arslanbisharat commented
Hi @gersonhiggins, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please make sure to add a live demo link to your README file. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-20 00:42 UTC, aamirkhan2478 requested changes
Hi @gersonhiggins , 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed

## Feedback about your video Presentation
- Your video presentation is very good but the only one thing is missing and that thing is you didn't show your code and you are not explaining which portion of the code you are proud of.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 00:42 UTC, aamirkhan2478 commented on index.html
- [ ] Your design is very good :clap: you did a very nice job :+1: but some items are missing like the `top-bar` and the `footer` so kindly add `top-bar` and footer in your project. Check below :point_down: the `top-bar` and `footer` screenshot :slightly_smiling_face: 

**Top Bar**
![Screenshot from 2023-04-20 04-08-25](https://user-images.githubusercontent.com/45226848/233224361-92b18acb-8c6d-4a4b-a51c-731a79a4c9ee.png)

**Home Footer**
![Screenshot from 2023-04-20 04-07-04](https://user-images.githubusercontent.com/45226848/233224421-34617c6e-49e2-4dab-b3e3-5ae40aefa488.png)

**About Footer**
![Screenshot from 2023-04-20 04-09-30](https://user-images.githubusercontent.com/45226848/233224408-fea8329a-bd9c-4616-a623-2227ec8e0d2d.png)

2023-04-20 00:42 UTC, aamirkhan2478 commented on index.html
> +    </header>
- [ ] Good effort :+1: but there are some issues like the spacing between links is too much and also the last link in the microverse provided a design with the last link is a red colour with a border but in your case when I hover it then it change to the red colour so kindly fix these issues :slightly_smiling_face: check below :point_down: comparison between your design and Behance design :+1: 

**Your Design**
![Screenshot from 2023-04-20 04-07-46](https://user-images.githubusercontent.com/45226848/233226161-8d34fbdc-78fd-4249-9e22-32e217ed6e06.png)

**Behance Deisgn**
![Screenshot from 2023-04-20 04-08-08](https://user-images.githubusercontent.com/45226848/233226171-59c1b7ba-b3e2-4dd2-bf5c-0582564fe517.png)

2023-04-20 00:42 UTC, aamirkhan2478 commented on index.html
> +        </div>
- [ ] Nice implementation :+1:  but when your see Behance design there are 2 speakers in one row but in your case, there are 3 speakers so kindly fix this issue also :slightly_smiling_face:  check  below :point_down:  the comparison between your design and Behance design :+1: 

**Your Design**
![Screenshot from 2023-04-20 05-22-58](https://user-images.githubusercontent.com/45226848/233226577-f20db00e-bed3-43ca-aedd-ccef2ac62c4d.png)

**Behance Design**
![Screenshot from 2023-04-20 04-08-59](https://user-images.githubusercontent.com/45226848/233226594-987f329a-b6fd-4004-bc6a-79985327e789.png)

2023-04-20 00:42 UTC, aamirkhan2478 commented on index.html
> +    </section>
- [ ] Very nice design :+1: but if your check Behance design in the `mobile version` there is a red colour button in your case, your using a link so kindly fix this issue :slightly_smiling_face: check below :point_down: comparison between your design and Behance design :+1:

**Your design**
![Screenshot from 2023-04-20 04-30-37](https://user-images.githubusercontent.com/45226848/233227083-f5d9833b-e13a-46a8-ae30-1fd8a67f6d56.png)

**Behance Design**
![Screenshot from 2023-04-20 04-30-58](https://user-images.githubusercontent.com/45226848/233227094-32a09334-d962-49dc-a0ea-9c4e0d4e1a86.png)

2023-04-20 00:42 UTC, aamirkhan2478 commented on README.md
> +[ProjectTemplate](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) - Project Template.
- [ ] Kindly use this line in the `Acknowledgments` section this is not an author so kindly remove this line from here and add in the `Acknowledgments` section in `line no.106` :slightly_smiling_face:

2023-04-20 16:04 UTC, DuaneDave requested changes
Hi @gersonhiggins 👋 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
- As the previous reviewer pointed out concerning the presentation linking from your PR, you still aren't sharing with us one important piece of code that you are very proud of and as such i recommend re recording a video including the above in order to meet the requirements.

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._

You can also consider:
- Using the correct structure of the readme template because you have removed most important section. NOTE: All section are important except the FAQ section which is optional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-20 16:04 UTC, DuaneDave commented on index.html
> +        <img src="./images/Ccsummit2015_logo.png">
Good job including the footer as previously requested but on the mobile, the footer is looking a bit messed up and i recommend fixing this in order to be consistent with the design.

NOTE: review the footer of the about page too since the same thing applies.

Your footer
<img width="220" alt="foot" src="https://user-images.githubusercontent.com/84930355/233416546-e95f5da5-2d3a-4b1d-b565-d60e4cdb3c13.PNG">

Behance
<img width="294" alt="behance foot" src="https://user-images.githubusercontent.com/84930355/233416797-ebcab856-1241-4cff-bf9d-747ce36d28ae.PNG">

2023-04-20 16:04 UTC, DuaneDave commented on README.md
> +[ProjectTemplate](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) - Project Template.
As previously mentioned, this part of the readme has a dedicated section called the acknowledgement section and there you can acknowledge the author of the template to make the readme well organized.

2023-04-20 16:04 UTC, DuaneDave commented on index.html
> +                </ul>
Good job including the top bar as previously requested, but you have overlooked the right spacing on the top bar. The behance version takes the same spacing as the main navigation but you have not so implemented. Consider working of the space in order to achieve that uniformity seen on behance.

Your navigation
<img width="947" alt="nav" src="https://user-images.githubusercontent.com/84930355/233420506-6ecb8e0b-5528-4451-87e6-3a1f27759abd.PNG">

Behance
<img width="623" alt="tra" src="https://user-images.githubusercontent.com/84930355/233420597-1e156557-9e5a-4dc6-8d81-831ae03c52e5.PNG">


Also consider removing the top bar on mobile version as it is visible which is not in line with the template given.

2023-04-20 16:52 UTC, divinecharlotte approved these changes
# Hello @gersonhiggins    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Descriptive PR ✔️
- Descriptive commit messages 👍 





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-24 14:36 UTC, merged